// theme/types.ts

export type ThemeColorKey =
  | 'color'
  | 'textSecondary'
  | 'textTertiary'
  | 'primary'
  | 'success'
  | 'danger'
  | 'warning'
  | 'gold'
  | 'error'
  | 'background'
  | 'surface'
  | 'surfaceSecondary'
  | 'primaryDark'
  | 'primaryLight'
  | 'primarySubtle'
  | 'successSubtle'
  | 'dangerSubtle'
  | 'warningSubtle'
  | 'goldSubtle'
  | 'icon'
  | 'overlay'
  | 'tabBar'
  | 'transparent'
  | 'darkText'
  | 'info'
  | 'infoSubtle'
  | 'white'
  | 'surfaceTertiary'
  | 'borderStrong'
  | 'borderColor'
  | 'color1' | 'color2' | 'color3' | 'color4' | 'color5' | 'color6' | 'color7' | 'color8' | 'color9' | 'color10' | 'color11' | 'color12';

export type AppTextVariant = 
  | 'titleLg' 
  | 'titleMd' 
  | 'titleSm' 
  | 'bodyLg' 
  | 'bodyMd' 
  | 'bodySm' 
  | 'label' 
  | 'caption';
