export const ROUTES = {
  TABS_HOME:              '/(tabs)/',
  TABS:                   '/(tabs)',
  ROUTINES:               '/routines',
  ROUTINES_FROM_HOME:     '/routines?source=home',
  ROUTINE_CREATE:         '/routine/create',
  EXERCISE_BROWSER:       '/(workouts)/exercise-browser',
  EXERCISE_BROWSER_ROUTINE: '/(workouts)/exercise-browser?target=routine',
  ACTIVE_WORKOUT:         '/(workouts)/active',
  WORKOUT_SUMMARY:        '/(workouts)/summary',
  REST_TIMER:             '/(workouts)/rest-timer',
  SETTINGS_PROFILE:       '/settings/profile',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  SETTINGS_PRIVACY:       '/settings/privacy',
  STATS:                  '/stats',
  STATS_WEIGHT:           '/stats/weight',
  HISTORY:                '/history',
  HISTORY_DETAIL:         '/history/[id]',
  ROUTINE_DETAIL:         '/routine/[id]',
} as const;
