import type * as SQLite from 'expo-sqlite';

export const version = 26;
export const name = '026_add_name_es_column';

const TRANSLATIONS: [string, string][] = [
  ['2 Handed Kettlebell Swing', 'Swing de Kettlebell a Dos Manos'],
  ['Seated Hip Adduction', 'Aducción de Cadera Sentado'],
  ['Arnold Shoulder Press', 'Press Arnold'],
  ['Axe Hold', 'Sostén de Hacha'],
  ['Barbell Ab Rollout', 'Rueda Abdominal con Barra'],
  ['Barbell Hack Squats', 'Sentadilla Hack con Barra'],
  ['Barbell Lunges Standing', 'Zancadas con Barra de Pie'],
  ['Barbell Reverse Wrist Curl', 'Curl de Muñeca Invertido con Barra'],
  ['Extensión de triceps', 'Extensión de Tríceps con Barra'],
  ['Barbell Wrist Curl', 'Curl de Muñeca con Barra'],
  ['Abdominal Stabilization', 'Estabilización Abdominal'],
  ['Bear Walk', 'Caminata de Oso'],
  ['Single Leg Extension', 'Extensión de Pierna Individual'],
  ['Bench Press', 'Press de Banca'],
  ['Benchpress Dumbbells', 'Press de Banca con Mancuernas'],
  ['Bench Press Narrow Grip', 'Press de Banca Agarre Cerrado'],
  ['Bent High Pulls', 'Jalón Alto Inclinado'],
  ['Remo con mancuernas', 'Remo con Mancuernas'],
  ['Bent-over Lateral Raises', 'Elevaciones Laterales Inclinado'],
  ['Bent Over Rowing', 'Remo Inclinado con Barra'],
  ['Bent Over Rowing Reverse', 'Remo Inclinado Agarre Invertido'],
  ['Biceps Curls With Barbell', 'Curl de Bíceps con Barra'],
  ['Curl de bíceps con mancuerna', 'Curl de Bíceps con Mancuerna'],
  ['Curl de biceps con barra Z', 'Curl de Bíceps con Barra Z'],
  ['Biceps Curl With Cable', 'Curl de Bíceps con Cable'],
  ['Body-Ups', 'Elevaciones de Cuerpo'],
  ['Braced Squat', 'Sentadilla con Disco'],
  ['Chest Press', 'Press de Pecho en Máquina'],
  ['Burpees', 'Burpees'],
  ['Butterfly', 'Mariposa'],
  ['Butterfly Narrow Grip', 'Mariposa Agarre Cerrado'],
  ['Butterfly Reverse', 'Mariposa Inversa'],
  ['Cable External Rotation', 'Rotación Externa con Cable'],
  ['Cable Woodchoppers', 'Leñador con Cable'],
  ['Calf Press Using Leg Press Machine', 'Press de Pantorrilla en Prensa'],
  ['Calf Raises on Hackenschmitt Machine', 'Elevación de Pantorrilla en Máquina Hack'],
  ['Chin Up', 'Dominada Supina'],
  ['Dominadas Supinas', 'Dominadas Supinas'],
  ['Close-grip Lat Pull Down', 'Jalón Dorsal Agarre Cerrado'],
  ['Cross-Bench Dumbbell Pullovers', 'Pullover con Mancuerna en Banco Cruzado'],
  ['Ball crunches', 'Abdominales en Pelota'],
  ['Abdominales', 'Abdominales'],
  ['Crunches on incline bench', 'Abdominales en Banco Inclinado'],
  ['Crunches on Machine', 'Abdominales en Máquina'],
  ['Crunches With Cable', 'Abdominales con Cable'],
  ['Crunches With Legs Up', 'Abdominales con Piernas Arriba'],
  ['Cycling', 'Ciclismo'],
  ['Deadbug', 'Bicho Muerto'],
  ['Deadhang', 'Colgado Pasivo'],
  ['Deadlifts', 'Peso Muerto'],
  ['Decline Bench Press Barbell', 'Press de Banca Declinado con Barra'],
  ['Decline Bench Press Dumbbell', 'Press de Banca Declinado con Mancuernas'],
  ['Decline Pushups', 'Flexiones Declinadas'],
  ['Deficit Deadlift', 'Peso Muerto con Déficit'],
  ['Diagonal Shoulder Press', 'Press de Hombro Diagonal'],
  ['Dips', 'Fondos en Paralelas'],
  ['Dips Between Two Benches', 'Fondos entre Dos Bancos'],
  ['Dumbbell Concentration Curl', 'Curl Concentrado con Mancuerna'],
  ['Dumbbell Goblet Squat', 'Sentadilla Goblet con Mancuerna'],
  ['Dumbbell Incline Curl', 'Curl Inclinado con Mancuerna'],
  ['Dumbbell Lunges Standing', 'Zancadas con Mancuernas de Pie'],
  ['Dumbbell Lunges Walking', 'Zancadas Caminando con Mancuernas'],
  ['Dumbbells on Scott Machine', 'Mancuernas en Máquina Scott'],
  ['Dumbbell Triceps Extension', 'Extensión de Tríceps con Mancuerna'],
  ['Face pull', 'Tirón Facial'],
  ['Flutter Kicks', 'Patadas de Aleteo'],
  ['Fly With Cable', 'Aperturas con Cable'],
  ['Fly With Dumbbells', 'Aperturas con Mancuernas'],
  ['Fly With Dumbbells, Decline Bench', 'Aperturas con Mancuernas en Banco Declinado'],
  ['Skullcrusher Dumbbells', 'Rompecráneos con Mancuernas'],
  ['Skullcrusher SZ-bar', 'Rompecráneos con Barra Z'],
  ['Front Raises with Plates', 'Elevaciones Frontales con Disco'],
  ['Elevaciones frontales', 'Elevaciones Frontales'],
  ['Front Squats', 'Sentadilla Frontal'],
  ['Front pull wide', 'Jalón Frontal Agarre Ancho'],
  ['Front Pull narrow', 'Jalón Frontal Agarre Cerrado'],
  ['Full Sit Outs', 'Sit Outs Completos'],
  ['Glute Bridge', 'Puente de Glúteos'],
  ['Good Mornings', 'Buenos Días'],
  ['Hammercurls', 'Curl Martillo'],
  ['Hammercurls on Cable', 'Curl Martillo con Cable'],
  ['Hand Grip', 'Pinza de Mano'],
  ['Handstand Pushup', 'Flexiones a Pino'],
  ['Hanging Leg Raises', 'Elevación de Piernas Colgado'],
  ['Hercules Pillars', 'Pilares de Hércules'],
  ['High Knee Jumps', 'Saltos con Rodillas Altas'],
  ['High Pull', 'Jalón Alto'],
  ['Hindu Squats', 'Sentadillas Hindú'],
  ['Hip Raise, Lying', 'Elevación de Cadera Acostado'],
  ['Barbell Hip Thrust', 'Empuje de Cadera con Barra'],
  ['Hollow Hold', 'Hollow Hold'],
  ['Hyperextensions', 'Hiperextensiones'],
  ['Incline Dumbbell Fly', 'Aperturas Inclinadas con Mancuernas'],
  ['Incline Dumbbell Row', 'Remo Inclinado con Mancuernas'],
  ['Incline Plank With Alternate Floor Touch', 'Plancha Inclinada con Toque Alterno'],
  ['Incline Push up', 'Flexiones Inclinadas'],
  ['Isometric Wipers', 'Limpiaparabrisas Isométricos'],
  ['Jogging', 'Trote'],
  ['Polichilenas', 'Polichinelas'],
  ['Cable Cross-over', 'Cruce de Cables'],
  ['Kettlebell Swings', 'Swing de Kettlebell'],
  ['Squats on Multipress', 'Sentadillas en Multipress'],
  ['Landmine press', 'Press Landmine'],
  ['Lateral Raises', 'Elevaciones Laterales'],
  ['Lateral Rows on Cable, One Armed', 'Remo Lateral con Cable a Un Brazo'],
  ['Lateral-to-Front Raises', 'Elevaciones Laterales a Frontales'],
  ['Lat Pull Down (Leaning Back)', 'Jalón Dorsal Inclinado'],
  ['Lat Pull Down (Straight Back)', 'Jalón Dorsal Espalda Recta'],
  ['Curl femoral', 'Curl Femoral'],
  ['Leg Curls (laying)', 'Curl Femoral Acostado'],
  ['Leg Curls (sitting)', 'Curl Femoral Sentado'],
  ['Leg Curls (standing)', 'Curl Femoral de Pie'],
  ['Curl cuadriceps', 'Curl de Cuádriceps'],
  ['Prensa de piernas', 'Prensa de Piernas'],
  ['Prensa de piernas cerrada', 'Prensa de Piernas Cerrada'],
  ['Press de piernas abierto', 'Prensa de Piernas Abierta'],
  ['Leg Press on Hackenschmidt Machine', 'Prensa de Piernas en Máquina Hack'],
  ['Levantamiento de piernas', 'Levantamiento de Piernas'],
  ['Leg Raises, Lying', 'Elevación de Piernas Acostado'],
  ['Leg Raises, Standing', 'Elevación de Piernas de Pie'],
  ['Leverage Machine Chest Press', 'Press de Pecho en Máquina de Palanca'],
  ['Leverage Machine Iso Row', 'Remo Iso en Máquina de Palanca'],
  ['L Hold', 'Sostén en L'],
  ['Diamond push ups', 'Flexiones Diamante'],
  ['Remo con polea', 'Remo con Polea'],
  ['Long-Pulley, Narrow', 'Polea Larga Agarre Cerrado'],
  ['Low Box Squat - Wide Stance', 'Sentadilla en Caja Baja - Stance Ancho'],
  ['Lying Rotator Cuff Exercise', 'Ejercicio de Manguito Rotador Acostado'],
  ['Press militar', 'Press Militar'],
  ['Muscle up', 'Muscle Up'],
  ['Negative Crunches', 'Abdominales Negativos'],
  ['Overhand Cable Curl', 'Curl con Cable por Encima'],
  ['Overhead Squat', 'Sentadilla Sobre la Cabeza'],
  ['Pause Bench', 'Press de Banca con Pausa'],
  ['Pendelay Rows', 'Remo Pendlay'],
  ['Perfect Push Up', 'Flexión Perfecta'],
  ['Flexiones de pica', 'Flexiones de Pica'],
  ['Sentadillas en pistol izquierda', 'Sentadilla Pistol Izquierda'],
  ['Plancha de antebrazo', 'Plancha de Antebrazo'],
  ['Preacher Curls', 'Curl en Banco Scott'],
  ['Prone Scapular Retraction - Arms at Side', 'Retracción Escapular Prono - Brazos al Lado'],
  ['Dominadas', 'Dominadas'],
  ['Pull Ups on Machine', 'Dominadas en Máquina'],
  ['Push Press', 'Push Press'],
  ['Lagartijas', 'Lagartijas'],
  ['Rack Deadlift', 'Peso Muerto en Rack'],
  ['Rear Delt Raises', 'Elevaciones de Deltoides Posterior'],
  ['Renegade Row', 'Remo Renegado'],
  ['Reverse Bar Curl', 'Curl Invertido con Barra'],
  ['Reverse Curl', 'Curl Invertido'],
  ['Reverse Grip Bench Press', 'Press de Banca Agarre Invertido'],
  ['Reverse Plank', 'Plancha Invertida'],
  ['Ring Dips', 'Fondos en Anillas'],
  ['Roman Chair', 'Silla Romana'],
  ['Romanian Deadlift', 'Peso Muerto Rumano'],
  ['Row', 'Remo'],
  ['Rowing, Lying on Bench', 'Remo Acostado en Banco'],
  ['Rowing, Seated', 'Remo Sentado'],
  ['Rowing, T-bar', 'Remo con Barra T'],
  ['Front Wood Chop', 'Leñador Frontal'],
  ['Run', 'Correr'],
  ['Run - Interval Training', 'Correr - Intervalos'],
  ['Run - Treadmill', 'Correr - Cinta'],
  ['Incline Bench Press - Dumbbell', 'Press Inclinado con Mancuernas'],
  ['Press de banca inclinado', 'Press de Banca Inclinado'],
  ['Incline Bench Press - MP', 'Press Inclinado en Multipress'],
  ['Shoulder Press, on Machine', 'Press de Hombro en Máquina'],
  ['Scissors', 'Tijeras'],
  ['Press de tríceps sentado', 'Press de Tríceps Sentado'],
  ['Side Bends on Machine', 'Flexiones Laterales en Máquina'],
  ['Shotgun Row', 'Remo Escopeta'],
  ['Shoulder Press, Barbell', 'Press de Hombro con Barra'],
  ['Shoulder Press, Dumbbells', 'Press de Hombro con Mancuernas'],
  ['Shoulder Press, on Multi Press', 'Press de Hombro en Multipress'],
  ['Shoulder Shrug', 'Encogimiento de Hombros'],
  ['Shrugs, Barbells', 'Encogimientos con Barra'],
  ['Shrugs, Dumbbells', 'Encogimientos con Mancuernas'],
  ['Shrugs on Multipress', 'Encogimientos en Multipress'],
  ['Side Crunch', 'Abdominal Lateral'],
  ['Side Dumbbell Trunk Flexion', 'Flexión Lateral de Tronco con Mancuerna'],
  ['Side-lying External Rotation', 'Rotación Externa Acostado de Lado'],
  ['Plancha de lado izquierdo', 'Plancha Lateral Izquierda'],
  ['Side to Side Push Ups', 'Flexiones de Lado a Lado'],
  ['Single-arm Preacher Curl', 'Curl Scott a Un Brazo'],
  ['Sitting Calf Raises', 'Elevación de Pantorrilla Sentado'],
  ['Skipping - Standard', 'Saltar la Cuerda'],
  ['Smith Machine Close-grip Bench Press', 'Press de Banca Agarre Cerrado en Smith'],
  ['Snach', 'Arranque'],
  ['Speed Deadlift', 'Peso Muerto Rápido'],
  ['Splinter Sit-ups', 'Abdominales Splinter'],
  ['Squat Jumps', 'Sentadilla con Salto'],
  ['Sentadillas', 'Sentadillas'],
  ['Squat Thrust', 'Sentadilla con Empuje'],
  ['Standing Bicep Curl', 'Curl de Bíceps de Pie'],
  ['Standing Calf Raises', 'Elevación de Pantorrilla de Pie'],
  ['Standing Rope Forearm', 'Enrollamiento de Cuerda de Pie'],
  ['Stationary Bike', 'Bicicleta Estática'],
  ['Stiff-legged Deadlifts', 'Peso Muerto Piernas Rígidas'],
  ['Straight-arm Pull Down (bar Attachment)', 'Jalón con Brazos Rectos (Barra)'],
  ['Straight-arm Pull Down (rope Attachment)', 'Jalón con Brazos Rectos (Cuerda)'],
  ['Sumo Deadlift', 'Peso Muerto Sumo'],
  ['Sumo Squats', 'Sentadilla Sumo'],
  ['Superman', 'Superman'],
  ['Thruster', 'Thruster'],
  ['Contragolpe de tríceps con mancuernas', 'Patada de Tríceps con Mancuernas'],
  ['Extension de triceps polea', 'Extensión de Tríceps en Polea'],
  ['Triceps Extensions on Cable With Bar', 'Extensión de Tríceps con Barra en Cable'],
  ['Triceps Machine', 'Máquina de Tríceps'],
  ['Trunk Rotation With Cable', 'Rotación de Tronco con Cable'],
  ['Rowing with TRX band', 'Remo con Banda TRX'],
  ['Turkish Get-Up', 'Levantamiento Turco'],
  ['Power Clean', 'Cargada de Potencia'],
  ['Underhand Lat Pull Down', 'Jalón Dorsal Agarre Supino'],
  ['Overhead Press', 'Press por Encima de la Cabeza'],
  ['Upper External Oblique', 'Oblicuo Externo Superior'],
  ['Upright Row, on Multi Press', 'Remo al Mentón en Multipress'],
  ['Upright Row, SZ-bar', 'Remo al Mentón con Barra Z'],
  ['Upright Row w/ Dumbbells', 'Remo al Mentón con Mancuernas'],
  ['V-Bar Pulldown', 'Jalón con Barra V'],
  ['Elevación de pantorrilla izquierda', 'Elevación de Pantorrilla Izquierda'],
  ['Flexión a pino contra la pared', 'Flexión a Pino contra la Pared'],
  ['Wall Pushup', 'Flexiones en Pared'],
  ['Wall Slides', 'Deslizamientos en Pared'],
  ['Asiento en pared', 'Sentadilla en Pared'],
  ['Weighted Step-ups', 'Subidas al Cajón con Peso'],
  ['Wide-grip Pulldown', 'Jalón Dorsal Agarre Ancho'],
  ['Dumbbell Push-Up', 'Flexiones sobre Mancuernas'],
  ['Barbell Lunges Walking', 'Zancadas Caminando con Barra'],
  ['One Arm Triceps Extensions on Cable', 'Extensión de Tríceps a Un Brazo en Cable'],
  ['Sloper hanging', 'Colgado en Sloper'],
  ['Empuje de tríceps en cable', 'Empuje de Tríceps en Cable'],
  ['Fingerboard 20 mm edge', 'Fingerboard Regleta 20mm'],
  ['Pullup on fingerboard', 'Dominada en Fingerboard'],
  ['Cable Rear Delt Fly', 'Aperturas de Deltoides Posterior con Cable'],
  ['Front Plate Raise', 'Elevación Frontal con Disco'],
  ['Incline Bench Reverse Fly', 'Aperturas Inversas en Banco Inclinado'],
  ['Rear Delt Raise', 'Elevación de Deltoides Posterior'],
  ['Squat con barra', 'Sentadilla con Barra'],
  ['Extensión de cuádriceps', 'Extensión de Cuádriceps'],
  ['Flexiones a pino', 'Flexiones a Pino'],
  ['Zone 2 Running', 'Carrera Zona 2'],
  ['Reverse Nordic Curl', 'Curl Nórdico Inverso'],
  ['Nordic Curl', 'Curl Nórdico'],
  ['Incline Skull Crush', 'Rompecráneos Inclinado'],
  ['Snatch Pull', 'Tirón de Arranque'],
  ['Seated Dumbbell Press', 'Press con Mancuernas Sentado'],
  ['Cable Fly', 'Aperturas con Cable'],
  ['Dumbbell Row', 'Remo con Mancuerna'],
  ['T-Bar Row', 'Remo con Barra T'],
  ['Chest Supported Row', 'Remo con Apoyo en Pecho'],
  ['Hack Squat', 'Sentadilla Hack'],
  ['Bulgarian Split Squat', 'Sentadilla Búlgara'],
  ['Hip Abduction Machine', 'Abducción de Cadera en Máquina'],
  ['Cable Kickback', 'Patada Trasera con Cable'],
  ['Seated Leg Curl', 'Curl Femoral Sentado'],
  ['Lying Leg Curl', 'Curl Femoral Acostado'],
  ['Standing Leg Curl', 'Curl Femoral de Pie'],
  ['Smith Machine Squat', 'Sentadilla en Smith'],
  ['Goblet Squat', 'Sentadilla Goblet'],
  ['Step Ups', 'Subidas al Cajón'],
  ['Box Jumps', 'Saltos al Cajón'],
  ['Calf Raises on Leg Press', 'Elevación de Pantorrilla en Prensa'],
  ['Donkey Calf Raise', 'Elevación de Pantorrilla Burro'],
  ['Machine Shoulder Press', 'Press de Hombro en Máquina'],
  ['Cable Lateral Raise', 'Elevación Lateral con Cable'],
  ['Dumbbell Front Raise', 'Elevación Frontal con Mancuerna'],
  ['Cable Face Pull', 'Tirón Facial con Cable'],
  ['Machine Fly', 'Aperturas en Máquina'],
  ['Pec Deck', 'Pec Deck'],
  ['Dumbbell Pullover', 'Pullover con Mancuerna'],
  ['Machine Row', 'Remo en Máquina'],
  ['Cable Row', 'Remo con Cable'],
  ['Inverted Row', 'Remo Invertido'],
  ['Meadows Row', 'Remo Meadows'],
  ['EZ Bar Curl', 'Curl con Barra Z'],
  ['Cable Hammer Curl', 'Curl Martillo con Cable'],
  ['Spider Curl', 'Curl Araña'],
  ['Bayesian Curl', 'Curl Bayesiano'],
  ['Triceps Dip Machine', 'Fondos de Tríceps en Máquina'],
  ['Overhead Triceps Extension', 'Extensión de Tríceps por Encima de la Cabeza'],
  ['JM Press', 'Press JM'],
  ['Farmer Walk', 'Caminata del Granjero'],
  ['Wrist Curl', 'Curl de Muñeca'],
  ['Reverse Wrist Curl', 'Curl de Muñeca Invertido'],
  ['Plate Pinch', 'Pinza de Disco'],
  ['Mountain Climbers', 'Escaladores'],
  ['Russian Twist', 'Giro Ruso'],
  ['Ab Wheel Rollout', 'Rueda Abdominal'],
  ['Pallof Press', 'Press Pallof'],
  ['Dead Bug', 'Bicho Muerto'],
  ['Plank', 'Plancha'],
  ['Side Plank', 'Plancha Lateral'],
  ['Woodchopper', 'Leñador'],
  ['Bicycle Crunch', 'Abdominales de Bicicleta'],
  ['Dragon Flag', 'Bandera del Dragón'],
  ['Clean and Jerk', 'Cargada y Envión'],
  ['Snatch', 'Arranque'],
  ['Clean', 'Cargada'],
  ['Rowing Machine', 'Máquina de Remo'],
  ['Elliptical', 'Elíptica'],
  ['Jump Rope', 'Saltar la Cuerda'],
  ['Battle Ropes', 'Cuerdas de Batalla'],
  ['Sled Push', 'Empuje de Trineo'],
  ['Sled Pull', 'Tirón de Trineo'],
  ['Hip Thrust Machine', 'Empuje de Cadera en Máquina'],
  ['Sissy Squat', 'Sentadilla Sissy'],
  ['Belt Squat', 'Sentadilla con Cinturón'],
  ['Zercher Squat', 'Sentadilla Zercher'],
  ['Jefferson Squat', 'Sentadilla Jefferson'],
  ['Pendulum Squat', 'Sentadilla Péndulo'],
  ['Leg Extension Machine', 'Extensión de Piernas en Máquina'],
  ['Smith Machine Lunge', 'Zancada en Smith'],
  ['Walking Lunge', 'Zancada Caminando'],
  ['Reverse Lunge', 'Zancada Inversa'],
  ['Curtsy Lunge', 'Zancada Cruzada'],
  ['Lateral Lunge', 'Zancada Lateral'],
  ['Cable Pull Through', 'Tirón de Cable Entre Piernas'],
  ['Single Leg Romanian Deadlift', 'Peso Muerto Rumano a Una Pierna'],
  ['Trap Bar Deadlift', 'Peso Muerto con Barra Hexagonal'],
];

export async function up(db: SQLite.SQLiteDatabase): Promise<void> {
  await db.execAsync('ALTER TABLE exercises ADD COLUMN name_es TEXT');

  for (const [englishName, spanishName] of TRANSLATIONS) {
    await db.runAsync(
      'UPDATE exercises SET name_es = ? WHERE name = ?',
      [spanishName, englishName],
    );
  }
}
